-- Create the table
create table public.questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  question_type text, -- 'MCQ', 'NAT', etc.
  options jsonb,      -- stores the array of options e.g. ["Option A", "Option B"]
  correct_answer text,
  subject text,
  marks numeric default 1,
  negative_marks numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.questions enable row level security;

-- Create a policy that allows anyone to read
create policy "Enable read access for all users" on public.questions
  for select using (true);

-- Create a policy that allows anyone to insert (for your setup tool)
-- Note: In production, you might want to restrict this to authenticated users only
create policy "Enable insert access for all users" on public.questions
  for insert with check (true);
